"""Planning endpoints: plan drafts are generated by tuttitrip-worker."""

from fastapi import APIRouter, HTTPException, status

from tuttitrip.planning.schemas import PlanJobRequest
from tuttitrip.planning.services import plan_job_service
from tuttitrip.shared.auth.api import CurrentUser
from tuttitrip.shared.db.api import SessionDep
from tuttitrip.shared.jobs.api import JobQueueDep
from tuttitrip.shared.jobs.schemas import JobAccepted
from tuttitrip.shared.jobs.services.job_queue import JobQueueUnavailableError
from tuttitrip.shared.jobs.services.worker_liveness import WorkerUnavailableError
from tuttitrip.shared.permissions.api import requires
from tuttitrip.shared.permissions.registry import Access, Feature
from tuttitrip.trips.services.trip_service import TripNotFoundError, TripRoleError

router = APIRouter(prefix="/planning", tags=["planning"])


@router.post(
    "/jobs",
    status_code=status.HTTP_202_ACCEPTED,
    dependencies=[requires(Feature.PLANNING_PROPOSALS, Access.WRITE)],
)
async def start_plan_job(
    data: PlanJobRequest, user: CurrentUser, session: SessionDep, queue: JobQueueDep
) -> JobAccepted:
    """Enqueue plan generation; poll ``GET /jobs/{workflow_id}`` for the result.

    The caller must be at least a co-host of the trip (404 when not on it).

    Args:
        data: Trip and free-text request.
        user: The authenticated organizer.
        session: Database session.
        queue: Job queue.

    Returns:
        The workflow id.
    """
    try:
        workflow_id = await plan_job_service.start_plan_generation(
            session, queue, user.sub, data
        )
    except TripNotFoundError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Trip not found") from exc
    except TripRoleError as exc:
        raise HTTPException(status.HTTP_403_FORBIDDEN, str(exc)) from exc
    except WorkerUnavailableError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc
    except JobQueueUnavailableError as exc:
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE, "Job queue unavailable"
        ) from exc
    return JobAccepted(workflow_id=workflow_id)
