"""Trip locations.

Revision ID: 8ea173f4861b
Revises: 243e9787efa9
Create Date: 2026-10-04 02:43:07.604171
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ea173f4861b"
down_revision: str | None = "243e9787efa9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_location_consents",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("until", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_trip_location_consents_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_location_consents_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "trip_id", "profile_id", name=op.f("pk_trip_location_consents")
        ),
    )
    op.create_table(
        "trip_locations",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("accuracy_m", sa.Double(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "accuracy_m IS NULL OR accuracy_m >= 0",
            name=op.f("ck_trip_locations_accuracy_range"),
        ),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90", name=op.f("ck_trip_locations_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180",
            name=op.f("ck_trip_locations_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_trip_locations_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_locations_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "trip_id", "profile_id", name=op.f("pk_trip_locations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trip_locations")
    op.drop_table("trip_location_consents")
    # ### end Alembic commands ###
