"""Trip invitations.

Revision ID: d8fd431ca322
Revises: d5b531aaa32c
Create Date: 2026-10-03 22:06:47.887469
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d8fd431ca322"
down_revision: str | None = "d5b531aaa32c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("uses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "max_uses >= 1", name=op.f("ck_trip_invitations_max_uses_positive")
        ),
        sa.CheckConstraint(
            "uses >= 0 AND uses <= max_uses",
            name=op.f("ck_trip_invitations_uses_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_invitations_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_trip_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_trip_invitations_trip_id"),
        "trip_invitations",
        ["trip_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_invitations_trip_id"), table_name="trip_invitations")
    op.drop_table("trip_invitations")
    # ### end Alembic commands ###
