"""Worker shared tables and embeddings.

Revision ID: 2316216d5b87
Revises: ccb417c53a87
Create Date: 2026-10-03 11:29:50.683131
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2316216d5b87"
down_revision: str | None = "ccb417c53a87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_kind", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    op.create_index(
        "ix_embeddings_source", "embeddings", ["source_kind", "source_id"], unique=False
    )
    op.create_table(
        "job_results",
        sa.Column("workflow_id", sa.String(length=300), nullable=False),
        sa.Column("workflow_name", sa.String(length=100), nullable=False),
        sa.Column("contract_version", sa.Integer(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workflow_id", name=op.f("pk_job_results")),
    )
    op.create_index(
        op.f("ix_job_results_workflow_name"),
        "job_results",
        ["workflow_name"],
        unique=False,
    )
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=200), nullable=False),
        sa.Column("env", sa.String(length=63), nullable=False),
        sa.Column("contract_version", sa.Integer(), nullable=False),
        sa.Column("min_contract_version", sa.Integer(), nullable=False),
        sa.Column("app_version", sa.String(length=200), nullable=False),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("pk_worker_heartbeats")),
    )
    op.create_index(
        op.f("ix_worker_heartbeats_env"), "worker_heartbeats", ["env"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worker_heartbeats_env"), table_name="worker_heartbeats")
    op.drop_table("worker_heartbeats")
    op.drop_index(op.f("ix_job_results_workflow_name"), table_name="job_results")
    op.drop_table("job_results")
    op.drop_index("ix_embeddings_source", table_name="embeddings")
    op.drop_table("embeddings")
    # ### end Alembic commands ###
