"""Accommodation search openings.

Revision ID: 243e9787efa9
Revises: 5b310321f6a9
Create Date: 2026-10-04 01:14:41.461655
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "243e9787efa9"
down_revision: str | None = "5b310321f6a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accommodation_search_openings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('airbnb', 'booking')",
            name=op.f("ck_accommodation_search_openings_platform"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_accommodation_search_openings_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accommodation_search_openings")),
    )
    op.create_index(
        op.f("ix_accommodation_search_openings_trip_id"),
        "accommodation_search_openings",
        ["trip_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    # Append-only: no UPDATE. DELETE stays allowed so a deleted trip cascades.
    op.execute(
        """
        CREATE FUNCTION accommodation_search_openings_no_update() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'accommodation_search_openings is append-only';
        END
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER accommodation_search_openings_no_update
        BEFORE UPDATE ON accommodation_search_openings
        FOR EACH STATEMENT EXECUTE FUNCTION accommodation_search_openings_no_update()
        """
    )


def downgrade() -> None:
    """Revert this revision."""
    op.execute(
        "DROP TRIGGER accommodation_search_openings_no_update "
        "ON accommodation_search_openings"
    )
    op.execute("DROP FUNCTION accommodation_search_openings_no_update()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_accommodation_search_openings_trip_id"),
        table_name="accommodation_search_openings",
    )
    op.drop_table("accommodation_search_openings")
    # ### end Alembic commands ###
