"""Place ratings and vetoes.

Revision ID: f3ed8c494ca7
Revises: 213f4a329ce3
Create Date: 2026-10-03 21:18:04.410856
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f3ed8c494ca7"
down_revision: str | None = "213f4a329ce3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_ratings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=True),
        sa.Column("updated_by_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(value = 'dont_want') = (reason_code IS NOT NULL)",
            name=op.f("ck_place_ratings_reason_iff_dont_want"),
        ),
        sa.CheckConstraint(
            "reason_code IN ('too_expensive', 'too_far', 'not_my_style', "
            "'too_crowded', 'too_hard_for_child', 'other')",
            name=op.f("ck_place_ratings_reason_code"),
        ),
        sa.CheckConstraint(
            "value IN ('want', 'dont_want', 'neutral')",
            name=op.f("ck_place_ratings_value"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_ratings_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_place_ratings_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_place_ratings_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_ratings")),
        sa.UniqueConstraint(
            "profile_id", "place_id", name=op.f("uq_place_ratings_profile_id")
        ),
    )
    op.create_index(
        op.f("ix_place_ratings_trip_id"), "place_ratings", ["trip_id"], unique=False
    )
    op.create_table(
        "place_vetoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_sub", sa.String(length=255), nullable=False),
        sa.Column("on_behalf", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_sub", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_vetoes_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_place_vetoes_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_place_vetoes_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_vetoes")),
    )
    op.create_index(
        op.f("ix_place_vetoes_trip_id"), "place_vetoes", ["trip_id"], unique=False
    )
    op.create_index(
        "uq_place_vetoes_active",
        "place_vetoes",
        ["profile_id", "place_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO role_grants (role_name, feature, level) "
        "VALUES ('user', 'profiles.feedback', 'WRITE') ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    """Revert this revision."""
    op.execute(
        "DELETE FROM role_grants "
        "WHERE role_name = 'user' AND feature = 'profiles.feedback'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_place_vetoes_active",
        table_name="place_vetoes",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index(op.f("ix_place_vetoes_trip_id"), table_name="place_vetoes")
    op.drop_table("place_vetoes")
    op.drop_index(op.f("ix_place_ratings_trip_id"), table_name="place_ratings")
    op.drop_table("place_ratings")
    # ### end Alembic commands ###
