"""Trip checkins.

Revision ID: 65807aa11765
Revises: 243e9787efa9
Create Date: 2026-10-04 02:23:07.815815
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65807aa11765"
down_revision: str | None = "243e9787efa9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_checkins",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("accommodation", sa.String(length=200), nullable=False),
        sa.Column("room", sa.String(length=20), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_trip_checkins_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_checkins_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trip_id", "profile_id", name=op.f("pk_trip_checkins")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trip_checkins")
    # ### end Alembic commands ###
