"""Account blocks and city fetches.

Revision ID: 477ae4f2a2d8
Revises: b81e5c2a7d14
Create Date: 2026-10-04 02:55:32.691298
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "477ae4f2a2d8"
down_revision: str | None = "b81e5c2a7d14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_blocks",
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("blocked_by", sa.String(length=255), nullable=False),
        sa.Column(
            "blocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_sub", name=op.f("pk_account_blocks")),
    )
    op.create_table(
        "city_fetch_attempts",
        sa.Column("workflow_id", sa.String(length=300), nullable=False),
        sa.Column("city_slug", sa.String(length=64), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workflow_id", name=op.f("pk_city_fetch_attempts")),
    )
    op.create_index(
        op.f("ix_city_fetch_attempts_reserved_at"),
        "city_fetch_attempts",
        ["reserved_at"],
        unique=False,
    )
    op.create_table(
        "city_fetches",
        sa.Column("city_slug", sa.String(length=64), nullable=False),
        sa.Column("osm_relation_id", sa.BigInteger(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stored", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_slug"],
            ["cities.slug"],
            name=op.f("fk_city_fetches_city_slug_cities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("city_slug", name=op.f("pk_city_fetches")),
    )
    # ### end Alembic commands ###
    # Move the worker's OSM fetch state out of job_results (backend#159). Only
    # rows that are complete and (for markers) whose city exists are moved and
    # then deleted; anything else stays in job_results untouched.
    op.execute(
        """
        INSERT INTO city_fetches (city_slug, osm_relation_id, fetched_at, stored)
        SELECT substr(j.workflow_id, 11),
               CAST(j.result ->> 'relation_id' AS bigint),
               CAST(j.result ->> 'fetched_at' AS timestamptz),
               COALESCE(CAST(j.result ->> 'stored' AS integer), 0)
        FROM job_results j
        WHERE j.workflow_id LIKE 'osm-fetch:%'
          AND jsonb_exists(j.result, 'relation_id')
          AND jsonb_exists(j.result, 'fetched_at')
          AND EXISTS (SELECT 1 FROM cities c WHERE c.slug = substr(j.workflow_id, 11))
        ON CONFLICT DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO city_fetch_attempts (workflow_id, city_slug, reserved_at)
        SELECT substr(j.workflow_id, 13),
               COALESCE(j.result ->> 'slug', ''),
               CAST(j.result ->> 'reserved_at' AS timestamptz)
        FROM job_results j
        WHERE j.workflow_id LIKE 'osm-attempt:%'
          AND jsonb_exists(j.result, 'reserved_at')
        ON CONFLICT DO NOTHING
        """
    )
    op.execute(
        """
        DELETE FROM job_results j
        WHERE (j.workflow_id LIKE 'osm-fetch:%'
          AND jsonb_exists(j.result, 'relation_id')
          AND jsonb_exists(j.result, 'fetched_at')
          AND EXISTS (SELECT 1 FROM cities c WHERE c.slug = substr(j.workflow_id, 11)))
           OR (j.workflow_id LIKE 'osm-attempt:%'
          AND jsonb_exists(j.result, 'reserved_at'))
        """
    )


def downgrade() -> None:
    """Revert this revision (the OSM fetch state goes back to job_results)."""
    op.execute(
        """
        INSERT INTO job_results (workflow_id, workflow_name, contract_version, result)
        SELECT 'osm-fetch:' || city_slug, 'fetch_place_candidates', 1,
               jsonb_build_object('relation_id', osm_relation_id,
                                  'fetched_at', fetched_at, 'stored', stored)
        FROM city_fetches
        ON CONFLICT DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO job_results (workflow_id, workflow_name, contract_version, result)
        SELECT 'osm-attempt:' || workflow_id, 'fetch_place_candidates', 1,
               jsonb_build_object('slug', city_slug, 'reserved_at', reserved_at)
        FROM city_fetch_attempts
        ON CONFLICT DO NOTHING
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city_fetches")
    op.drop_index(
        op.f("ix_city_fetch_attempts_reserved_at"), table_name="city_fetch_attempts"
    )
    op.drop_table("city_fetch_attempts")
    op.drop_table("account_blocks")
    # ### end Alembic commands ###
