"""Named invitations: the profile a link hands over.

Revision ID: 2aba684f6abc
Revises: 5b310321f6a9
Create Date: 2026-10-04 00:53:46.621589
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2aba684f6abc"
down_revision: str | None = "5b310321f6a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trip_invitations", sa.Column("profile_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_trip_invitations_profile_id_profiles"),
        "trip_invitations",
        "profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_trip_invitations_profile_id_profiles"),
        "trip_invitations",
        type_="foreignkey",
    )
    op.drop_column("trip_invitations", "profile_id")
    # ### end Alembic commands ###
