"""Permissions: roles, grants, audit log; trip members.

Seeds the system roles: ``user`` (applies to every authenticated user, explicit
leaves outside ``admin.*``) and ``superadmin`` (``*`` WRITE, documentation only:
the Auth0 ``admin`` claim confers it and the API never assigns it). Makes
``permission_audit`` append-only and backfills trip owners as hosts.

The seed is a frozen copy: later changes to defaults need a new migration.

Revision ID: 1c3eca9c16c6
Revises: 2316216d5b87
Create Date: 2026-10-03 14:53:30.979908
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1c3eca9c16c6"
down_revision: str | None = "2316216d5b87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Default role "user": explicit leaves, nothing under admin.* (tested).
USER_ROLE_GRANTS: tuple[tuple[str, str], ...] = (
    ("accounts.profile", "WRITE"),
    ("trips.core", "WRITE"),
    ("trips.members", "WRITE"),
    ("trips.invitations", "WRITE"),
    ("profiles.core", "WRITE"),
    ("profiles.preferences", "WRITE"),
    ("profiles.feedback", "WRITE"),
    ("interview", "WRITE"),
    ("planning.proposals", "WRITE"),
    ("planning.fairness", "READ"),
    ("planning.linter", "READ"),
    ("accommodation", "WRITE"),
    ("search", "READ"),
    ("expenses.core", "WRITE"),
    ("expenses.settlement", "READ"),
    ("jobs", "WRITE"),
)


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("actor_sub", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_sub", sa.String(length=255), nullable=True),
        sa.Column("target_role", sa.String(length=50), nullable=True),
        sa.Column("change", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_audit")),
    )
    op.create_index(
        op.f("ix_permission_audit_target_sub"),
        "permission_audit",
        ["target_sub"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_roles")),
    )
    op.create_table(
        "user_grants",
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column("feature", sa.String(length=100), nullable=False),
        sa.Column(
            "level",
            sa.Enum("READ", "WRITE", name="access_level", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("granted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('READ', 'WRITE')", name=op.f("ck_user_grants_level")
        ),
        sa.PrimaryKeyConstraint("user_sub", "feature", name=op.f("pk_user_grants")),
    )
    op.create_table(
        "role_grants",
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("feature", sa.String(length=100), nullable=False),
        sa.Column(
            "level",
            sa.Enum("READ", "WRITE", name="access_level", native_enum=False, length=10),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('READ', 'WRITE')", name=op.f("ck_role_grants_level")
        ),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["roles.name"],
            name=op.f("fk_role_grants_role_name_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_name", "feature", name=op.f("pk_role_grants")),
    )
    op.create_table(
        "trip_members",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "member",
                "co_host",
                "host",
                name="trip_role",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('member', 'co_host', 'host')", name=op.f("ck_trip_members_role")
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_members_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trip_id", "user_sub", name=op.f("pk_trip_members")),
    )
    op.create_index(
        op.f("ix_trip_members_user_sub"), "trip_members", ["user_sub"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["roles.name"],
            name=op.f("fk_user_roles_role_name_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_sub", "role_name", name=op.f("pk_user_roles")),
    )
    op.create_index(
        op.f("ix_user_roles_role_name"), "user_roles", ["role_name"], unique=False
    )
    # ### end Alembic commands ###

    roles = sa.table(
        "roles",
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        roles,
        [
            {
                "name": "user",
                "description": "Każdy zalogowany użytkownik (domyślna)",
                "is_system": True,
            },
            {
                "name": "superadmin",
                "description": "Wszystko (*:WRITE); tylko z claimu Auth0 admin",
                "is_system": True,
            },
        ],
    )
    role_grants = sa.table(
        "role_grants",
        sa.column("role_name", sa.String),
        sa.column("feature", sa.String),
        sa.column("level", sa.String),
    )
    op.bulk_insert(
        role_grants,
        [
            {"role_name": "user", "feature": feature, "level": level}
            for feature, level in USER_ROLE_GRANTS
        ]
        + [{"role_name": "superadmin", "feature": "*", "level": "WRITE"}],
    )

    op.execute(
        """
        CREATE FUNCTION permission_audit_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'permission_audit is append-only';
        END
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER permission_audit_append_only
        BEFORE UPDATE OR DELETE OR TRUNCATE ON permission_audit
        FOR EACH STATEMENT EXECUTE FUNCTION permission_audit_append_only()
        """
    )

    op.execute(
        "INSERT INTO trip_members (trip_id, user_sub, role) "
        "SELECT id, owner_sub, 'host' FROM trips"
    )


def downgrade() -> None:
    """Revert this revision."""
    # Dropping the table drops its trigger; the function goes separately.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_role_name"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_trip_members_user_sub"), table_name="trip_members")
    op.drop_table("trip_members")
    op.drop_table("role_grants")
    op.drop_table("user_grants")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permission_audit_target_sub"), table_name="permission_audit")
    op.drop_table("permission_audit")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION permission_audit_append_only()")
