"""Access tokens.

Revision ID: d5b531aaa32c
Revises: 2647fc89c3ae
Create Date: 2026-10-03 21:05:12.160045
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d5b531aaa32c"
down_revision: str | None = "2647fc89c3ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("VOTE", name="token_scope", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_access_tokens_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_access_tokens_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_access_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_access_tokens_profile_id"),
        "access_tokens",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_tokens_trip_id"), "access_tokens", ["trip_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_access_tokens_trip_id"), table_name="access_tokens")
    op.drop_index(op.f("ix_access_tokens_profile_id"), table_name="access_tokens")
    op.drop_table("access_tokens")
    # ### end Alembic commands ###
