"""Places catalog: cities, places, prices, transit fares; user READ grant.

Revision ID: 22159f26a4eb
Revises: 1c3eca9c16c6
Create Date: 2026-10-03 20:20:58.024824
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "22159f26a4eb"
down_revision: str | None = "1c3eca9c16c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("center_lat", sa.Double(), nullable=False),
        sa.Column("center_lon", sa.Double(), nullable=False),
        sa.Column("bbox_south", sa.Double(), nullable=False),
        sa.Column("bbox_west", sa.Double(), nullable=False),
        sa.Column("bbox_north", sa.Double(), nullable=False),
        sa.Column("bbox_east", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_cities")),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("osm_type", sa.String(length=8), nullable=True),
        sa.Column("osm_id", sa.BigInteger(), nullable=True),
        sa.Column("google_place_id", sa.String(length=200), nullable=True),
        sa.Column(
            "opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hours_source_url", sa.Text(), nullable=True),
        sa.Column(
            "hours_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("hours_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("typical_visit_min", sa.Integer(), nullable=False),
        sa.Column(
            "segment_km", sa.Double(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "transfer_min", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "queue_min", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("stairs", sa.Double(), server_default=sa.text("0"), nullable=False),
        sa.Column("wheelchair", sa.Boolean(), nullable=True),
        sa.Column(
            "indoor", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "iconic", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("cuisine", sa.String(length=100), nullable=True),
        sa.Column(
            "diet_tags",
            sa.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "category IN ('attraction', 'museum', 'restaurant', 'cafe', 'park', "
            "'viewpoint', 'shopping', 'nightlife', 'entertainment', 'lodging')",
            name=op.f("ck_places_category"),
        ),
        sa.CheckConstraint(
            "osm_type IN ('node', 'way', 'relation')", name=op.f("ck_places_osm_type")
        ),
        sa.CheckConstraint("source IN ('sheet', 'osm')", name=op.f("ck_places_source")),
        sa.CheckConstraint(
            "(osm_type IS NULL) = (osm_id IS NULL)", name=op.f("ck_places_osm_ref")
        ),
        sa.CheckConstraint("lat BETWEEN -90 AND 90", name=op.f("ck_places_lat")),
        sa.CheckConstraint("lon BETWEEN -180 AND 180", name=op.f("ck_places_lon")),
        sa.CheckConstraint("stairs BETWEEN 0 AND 1", name=op.f("ck_places_stairs")),
        sa.CheckConstraint(
            "typical_visit_min >= 0 AND segment_km >= 0 "
            "AND transfer_min >= 0 AND queue_min >= 0",
            name=op.f("ck_places_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["city_slug"], ["cities.slug"], name=op.f("fk_places_city_slug_cities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
        sa.UniqueConstraint("osm_type", "osm_id", name=op.f("uq_places_osm_type")),
    )
    op.create_index(op.f("ix_places_category"), "places", ["category"], unique=False)
    op.create_index(op.f("ix_places_city_slug"), "places", ["city_slug"], unique=False)
    op.create_table(
        "transit_fares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_slug", sa.String(length=64), nullable=False),
        sa.Column("ticket_type", sa.String(length=32), nullable=False),
        sa.Column("person_category", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_transit_fares_amount")),
        sa.ForeignKeyConstraint(
            ["city_slug"],
            ["cities.slug"],
            name=op.f("fk_transit_fares_city_slug_cities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transit_fares")),
        sa.UniqueConstraint(
            "city_slug",
            "ticket_type",
            "person_category",
            name=op.f("uq_transit_fares_city_slug"),
        ),
    )
    op.create_index(
        op.f("ix_transit_fares_city_slug"), "transit_fares", ["city_slug"], unique=False
    )
    op.create_table(
        "place_prices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_category", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ticket_category IN ('adult', 'child', 'senior', 'student', 'family')",
            name=op.f("ck_place_prices_ticket_category"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_place_prices_amount")),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_prices_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_prices")),
        sa.UniqueConstraint(
            "place_id", "ticket_category", name=op.f("uq_place_prices_place_id")
        ),
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO role_grants (role_name, feature, level) "
        "VALUES ('user', 'places.catalog', 'READ') ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    """Revert this revision."""
    op.execute(
        "DELETE FROM role_grants "
        "WHERE role_name = 'user' AND feature = 'places.catalog'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place_prices")
    op.drop_index(op.f("ix_transit_fares_city_slug"), table_name="transit_fares")
    op.drop_table("transit_fares")
    op.drop_index(op.f("ix_places_city_slug"), table_name="places")
    op.drop_index(op.f("ix_places_category"), table_name="places")
    op.drop_table("places")
    op.drop_table("cities")
    # ### end Alembic commands ###
