"""Trip photos.

Revision ID: 6a471240ae34
Revises: a7bad57ce3b3
Create Date: 2026-10-04 02:32:04.547246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a471240ae34"
down_revision: str | None = "a7bad57ce3b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("author_sub", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("thumbnail_type", sa.String(length=20), nullable=False),
        sa.Column("thumbnail", sa.LargeBinary(), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_photos_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_photos")),
    )
    op.create_index(
        "ix_trip_photos_trip_created",
        "trip_photos",
        ["trip_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trip_photos_trip_created", table_name="trip_photos")
    op.drop_table("trip_photos")
    # ### end Alembic commands ###
